const RoomData = [
    {
      roomNumber: "101",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "102",
      roomType: "PNQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "103",
      roomType: "SNK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "104",
      roomType: "NK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "105",
      roomType: "SNK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "106",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "107",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "108",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "109",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "110",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "111",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "112",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "113",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "114",
      roomType: "NK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "115",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "116",
      roomType: "ENQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "117",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "118",
      roomType: "PNQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "119",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "120",
      roomType: "PNQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "121",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "122",
      roomType: "SNK1",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "123",
      roomType: "ENQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "124",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "125",
      roomType: "NKEF",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "126",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "128",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "130",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "132",
      roomType: "NK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "134",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "136",
      roomType: "SKN1",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "138",
      roomType: "SNK1",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    }, 



    // SECOND FLOOR



    {
      roomNumber: "201",
      roomType: "NQQB",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "202",
      roomType: "NK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "203",
      roomType: "SNK1",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "204",
      roomType: "NQQB",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "205",
      roomType: "SNK1",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "206",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "207",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "208",
      roomType: "NK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "209",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "210",
      roomType: "NK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "211",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "212",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "213",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "214",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "215",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "216",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "217",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "218",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "219",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "220",
      roomType: "NK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "221",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "222",
      roomType: "ENQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "223",
      roomType: "NK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "224",
      roomType: "PNQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "225",
      roomType: "NK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "226",
      roomType: "PNQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "227",
      roomType: "NKEF",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "228",
      roomType: "SNK1",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "229",
      roomType: "NKEF",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "230",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "232",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "234",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "236",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "238",
      roomType: "NK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "240",
      roomType: "NK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "242",
      roomType: "SNK1",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "244",
      roomType: "SNK1",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },



    //THIRD FLOOR



    {
      roomNumber: "301",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "302",
      roomType: "ENQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "304",
      roomType: "ENQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "305",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "306",
      roomType: "NQQB",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "307",
      roomType: "NQQB",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "308",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "309",
      roomType: "NK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "310",
      roomType: "NK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "311",
      roomType: "NQQB",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "312",
      roomType: "NKEX1",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "313",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "314",
      roomType: "NKEX1",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "315",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "316",
      roomType: "NKEX1",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "317",
      roomType: "SNK1",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "318",
      roomType: "NKEX1",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "319",
      roomType: "SNK1",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "320",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "321",
      roomType: "NK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "322",
      roomType: "NQQB",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "323",
      roomType: "NQQB",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "324",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "325",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "326",
      roomType: "NK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "327",
      roomType: "NQQB",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "328",
      roomType: "NK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "329",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "330",
      roomType: "NQQB",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "331",
      roomType: "NQQB",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "332",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "333",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "334",
      roomType: "NQQB",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "335",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "336",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "337",
      roomType: "NK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "338",
      roomType: "NK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "339",
      roomType: "NQQB",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "340",
      roomType: "ENQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "341",
      roomType: "NKEF",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "342",
      roomType: "PNQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "343",
      roomType: "NKEF",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "344",
      roomType: "PNQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "346",
      roomType: "SKN1",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "348",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "350",
      roomType: "NQQB",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "352",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "354",
      roomType: "NQQB",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "356",
      roomType: "NK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "358",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "360",
      roomType: "NKEF",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "362",
      roomType: "NKEF",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },



    //FOURTH FLOOR



    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },


  ];
  
  export default RoomData;