const RoomData = [
  {
    roomNumber: "101",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "102",
    roomType: "1QP",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "103",
    roomType: "1KFJ",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.5",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "104",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "105",
    roomType: "1KFJ",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.5",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "106",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "107",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "108",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "109",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "110",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "111",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "112",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "113",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "114",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "115",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "116",
    roomType: "2QE",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.3",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "117",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "118",
    roomType: "2QP",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "119",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "120",
    roomType: "2QP",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "121",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "122",
    roomType: "1KS",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.3",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "123",
    roomType: "2QE",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.3",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "124",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "125",
    roomType: "1KF",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "126",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "128",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "130",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "132",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "134",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "136",
    roomType: "SKN1",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.3",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "138",
    roomType: "1KS",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.3",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },

  // SECOND FLOOR

  {
    roomNumber: "201",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "202",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "203",
    roomType: "1KS",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.3",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "204",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "205",
    roomType: "1KS",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.3",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "206",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "207",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "208",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "209",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "210",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "211",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "212",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "213",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "214",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "215",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "216",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "217",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "218",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "219",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "220",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "221",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "222",
    roomType: "2QE",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.3",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "223",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "224",
    roomType: "2QP",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "225",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "226",
    roomType: "2QP",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "227",
    roomType: "1KF",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "228",
    roomType: "1KS",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.3",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "229",
    roomType: "1KF",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "230",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "232",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "234",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "236",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "238",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "240",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "242",
    roomType: "1KS",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.3",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "244",
    roomType: "1KS",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.3",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },

  //THIRD FLOOR

  {
    roomNumber: "301",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "302",
    roomType: "2QE",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.3",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "303",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "304",
    roomType: "2QE",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.3",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "305",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "306",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "307",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "308",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "309",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "310",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "311",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "312",
    roomType: "1KES",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.4",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "313",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "314",
    roomType: "1KES",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.4",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "315",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "316",
    roomType: "1KES",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.4",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "317",
    roomType: "1KS",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.3",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "318",
    roomType: "1KES",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.4",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "319",
    roomType: "1KS",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.3",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "320",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "321",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "322",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "323",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "324",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "325",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "326",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "327",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "328",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "329",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "330",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "331",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "332",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "333",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "334",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "335",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "336",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "337",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "338",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "339",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "340",
    roomType: "2QE",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.3",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "341",
    roomType: "1KF",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "342",
    roomType: "2QP",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "343",
    roomType: "1KF",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "344",
    roomType: "2QP",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "346",
    roomType: "SKN1",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.3",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "348",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "350",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "352",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "354",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "356",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "358",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "360",
    roomType: "1KF",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "362",
    roomType: "1KF",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },

  //FOURTH FLOOR

  {
    roomNumber: "401",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "402",
    roomType: "1KS",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.3",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "403",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "404",
    roomType: "1KS",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.3",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "405",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "406",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "407",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "408",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "409",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "410",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "411",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "412",
    roomType: "1KES",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.4",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "413",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "414",
    roomType: "1KES",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.4",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "415",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "416",
    roomType: "1KES",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.4",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "417",
    roomType: "1KS",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.3",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "418",
    roomType: "1KES",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.4",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "419",
    roomType: "1KS",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.3",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "420",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "421",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "422",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "423",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "424",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "425",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "426",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "YES",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "427",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "428",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "429",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "430",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "431",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "432",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "433",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "434",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "435",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "436",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "437",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "438",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "439",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "440",
    roomType: "2QE",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.3",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "441",
    roomType: "1KF",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "442",
    roomType: "2QP",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "443",
    roomType: "1KF",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "444",
    roomType: "2QP",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "446",
    roomType: "SKN1",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.3",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "448",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "450",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "452",
    roomType: "2Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "454",
    roomType: "2QB",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.2",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "456",
    roomType: "1K",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "458",
    roomType: "1Q",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "460",
    roomType: "1KF",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
  {
    roomNumber: "462",
    roomType: "1KF",
    roomStatus: "Dirty",
    coStatus: "DUE",
    workload: "1.1",
    nearElevator: "NO",
    extras: "",
    assignedtoHSK: "",
    assignedtoSUP: "",
    time_stamp: "",
  },
];

export default RoomData;
