const RoomData = [
    {
      roomNumber: "101",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "102",
      roomType: "PNQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "103",
      roomType: "SNK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "104",
      roomType: "NK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "105",
      roomType: "SNK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "106",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "107",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "108",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "109",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "110",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "111",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "112",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "113",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "114",
      roomType: "NK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "115",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "116",
      roomType: "ENQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "117",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "118",
      roomType: "PNQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "119",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "120",
      roomType: "PNQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "121",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "122",
      roomType: "SNK1",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "123",
      roomType: "ENQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "124",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "125",
      roomType: "NKEF",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "126",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "128",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "130",
      roomType: "NQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "132",
      roomType: "NK",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "134",
      roomType: "NQQ",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "136",
      roomType: "SKN1",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "138",
      roomType: "SNK1",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    }, 
    // SECOND FLOOR
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },
    {
      roomNumber: "101",
      roomType: "",
      roomStatus: "Dirty",
      coStatus: "DUE",
      people: "",
      arrival: "",
      departs: "",
      extras: "",
      early_ci: "",
    },


  ];
  
  export default RoomData;